wole_list=[]
wole_list.append(10)
wole_list.append(20)
wole_list.append(30)
wole_list.append(40)
wole_list.insert(1,15)
wole_list.extend([50,60,70])
wole_list.pop()
wole_list.sort()
index_of_30=wole_list.index(30)
print(wole_list)
print("Index of 30:",index_of_30)